Add files via upload
daniil934/test1 pull request #3
Opened 2022-07-26 17:27 UTC by daniil934

2022-07-26 18:33 UTC, sjnm8 requested changes

2022-07-26 18:33 UTC, sjnm8 commented on stack.txt
> +a = []
1. Загружай файлы через git(не через вебсайт)
2. Новые таски делай в новой ветке
3. Удали лишнюю папку Downloads

2022-07-26 18:33 UTC, sjnm8 commented on stack.txt
> +
С массивом идея правильная, однако это еще не стек.
Используй класс
```rb
class Stack
...
end
```

Твой класс должен отвечать интерфейсу, который я тебе давал в задаче.
Т.е. например метод `peek` (Get the value of the top element without removing it)
```rb
stack = Stack.new
stack.peek # nil
stack.push('c')
stack.peek # 'c'
```

Или метод `pop`
```rb
stack = Stack.new
stack.push('a)
stack.push('b')
stack.pop # 'b'
stack.pop # 'a'
```
массив в данном случае будет использоваться внутри методов
например:
метод `pop` может выглядеть так:
```rb
class Stack
  def pop
    arr.pop
  end
  ...
end
```

`arr`  в данном случае инстанс переменная, которую ты инициализиурешь пустым массивом в конструкторе(метод `initialize`)
Остальные методы, нужно сделать по подобию.

2022-07-26 18:33 UTC, sjnm8 commented on stack.txt
> +      expect(a).to eq(["c", "p"])
Тестировать так же нужно методы экземпляра класса (instance)
```rb
it 'appends value in underlying instance variable' do
  stack = Stack.new
  stack.push('a')

  expect(stack.arr).to eq(['a'])
end
```
Чтобы такой тест прошёл, нужно, чтобы у инстас переменной был геттер (`attr_reader`).
Почитай что такое геттеры, сеттеры и про `attr_reader`

2022-07-26 18:33 UTC, sjnm8 commented on stack2.txt
> +a.reverse!()
Ты развернул строку без помощи стека. Хорошо, что выучил этот метод, он тоже полезный.
Но нужно развернуть строку именно через стек.
В этом файле тебе нужно подключить файл(смотри `require`), где объявлен класс стека и дальше написать другой класс например `StringReverser`, который умеет разворачивать строки.

```rb
reverser = StringReverser.new
reverser.reverse('cpu') # 'upc'
```

и соответсвенно тесты к этому делу
 
```rb
it 'reverses string' do
  reverser = StringReverser.new
 expect(reverser.reverse('abcde')).to eq 'edcba'
end
```

Еще в руби, опускаются скобки, если у функции нет аргументов, т.е. просто пишешь `a.reverse!`

2022-07-26 18:33 UTC, sjnm8 commented on stack2.txt
> +      raise "Error"
Для чего ты здесь проверяешь что `a` массив?
Я имел ввиду, что проверяй аргументы функции
```rb
StringReverser.new.reverse(12) # Тут должна быть ошибка, что 12 не строка
StringReverser.new.reverse('12') # Тут ошибки нет, возвращается '21'
StringReverser.new.reverse([]) # Тут тоже ошибка

# В тестах проверяется, например, так:
expect(StringReverser.new.reverse([])).to raise_error(InvalidArgument)
```
Про это пока не думай, сделай все что я тебе написал.
Подвегу итог здесь, что нужно сделать.

1. Написать в отдельном файле класс стек у которого есть все методы из задачи, с тестами на них
2. Написать в отдельном файле класс, который разворачивает строку, используя стек.
3. Поправить все замечания описанные выше(лишние файлы, неправильные разрешения) и залить изменения через git(консоль).

Подсказка по пункту 2.
Чтобы реализовать данный метод, нужно закодировать следующий алгоритм:
1. Разбиваем строку на массив символов(букв)
2. В цикле кладём в стек каждую букву. (подсказка завершить цикл можно, когда метод `is_empty` на стеке вернет `true` или когда метод `pop` вернет `nil`
4. Дальше достаем из стека каждую букву (например, в массив и потом преобразуем в строку или заводим переменную с пустой строкой и туда добавляем буквы
5. Возвращаем полученную строку.

2022-07-27 14:15 UTC, daniil934 commented
class Stack
  a = []
  a.push "c"
  a.push "p"
  a.push "u"
  a.pop 
  puts a 

  def pop
    a.pop
  end

  def peek
    a.peek
  end

end

stack = Stack.new
stack.peek # nil
stack.push('c')
stack.peek # 'c'

2022-07-27 14:51 UTC, sjnm8 commented
> ```ruby
> class Stack
>   a = [] # тебе нужно сохранить пустой массив в инстанс переменную(подсказка, они начинаются с @)
>   a.push "c" # ты добавляешь в стек только через метод push на классе, а не массива
>   a.push "p" # в классах все действия пишут в методах, в твоем случае это сработает, но толку от этого не будет
>   a.push "u"
>   a.pop 
>   puts a 
> 
>   def pop
>     a.pop
>   end
> 
>   def peek
>     a.peek # у массива нет метода peek
>   end
> 
> end
> 
> stack = Stack.new
> stack.peek # nil
> stack.push('c')
> stack.peek # 'c'
> ```

твой класс должен выглядеть так
```rb
class Stack
  # тут нужно объявить attr_reader для переменной, в которой лежит пустой массив из конструктора
  # констуктор - это метод initialize, этот метод вызывается, когда ты объявляешь новый экзмепляр класса  (Stack.new)
  # попробуй например в этом методе вызвать puts 'test' и потом когда ты просто вызовешь Stack.new, он исполнит эту комманду

  def initialize
    # тут нужно объявить инстанс переменную для пустово массива
  end

  def push(arg)
    # тут нужно положить аргумент arg в массив, который объявлен в коснтрукторе (доступ через attr_reader) 
  end

  def pop
    # тут ты берешь из массива последний элемент (с удалением его из массива)
  end

  def peek
    # тут ты просто возвращаешь последний элемент массива (без удаления элемента из массива)
  end
end
```

Тесты должны отработать
```rb
RSpec.describe Stack do
  it 'pushes element on top of stack(кладёт элемент на стек)' do
    stack = Stack.new
    stack.push('a')
    stack.push('b')
    # проверяем, что вызвав 2 раза метод, в массив, который спрятан внутри класса в инстанс переменной, пришло 2 элемента
    expect(stack.arr).to eq ['a', 'b']
  end

  it 'removes element from stack(удаляет элемент из стека)' do
    stack = Stack.new
    # проверяем, что пустой стек возвращает nil (если массив внутри класса пустой)
    expect(stack.pop).to nil

    stack.push('a')
    stack.push('b')
   
   # проверяем что после того, как положили 2 элемента в массив, он возвращает их в нужном порядке(сначала последний, потом первый)
    expect(stack.pop).to eq 'b'
    expect(stack.pop).to eq 'a'
    expect(stack.pop).to nil # тут элементы снова кончились
  end

  it 'shows element on top of stack(показывает верхний элемент на стеке)' do
    stack = Stack.new
    stack.push('a')
    stack.push('b')
    
    # проверяем, что положили 2 элемента
    expect(stack.arr).to eq ['a', 'b']
    
    # проверяем, что метод возвращает элемент, который был добавлен последним   
    expect(stack.peek).to eq 'b'

   # проверяем, что метод peek не удалил элемент, а только показал его
    expect(stack.arr).to eq ['a', 'b']
  end
end
```



Разница между возвращаем элемент и отображаем элемент в том, что
`puts` просто печатает в консоль:
```irb
irb(main):002:0> puts 'a'
a
=> nil                                              
irb(main):003:0> 
```

При этом возвращаемое значение nil, как ты видишь из вывода от irb

```irb
irb(main):008:1* def test_method(arg)
irb(main):009:1*   puts arg
irb(main):010:0> end
=> :test_method # тут вернулось название метода, который мы объявили, в это пока сильно не вникай, потом поймешь
irb(main):011:0> test_method(1)
1 # метод напечатал в консоль аргумент
=> nil  # метод вернул значение nil, потому что метод puts возвращает nil
irb(main):012:0> 
```

Теперь, чтобы метод реально что-то вернул, нужно возвращать значение из метода:
```irb
irb(main):012:1* def pop
irb(main):013:1*   return 1
irb(main):014:0> end
=> :pop
irb(main):015:0> pop
=> 1 # метод возвращает то, что мы указали в return. Однако в случае с руби, если не указывать return, то метод возвращает последню строчку(попробуй убрать return и проверить)
irb(main):016:0> 
```

Курсы codeacademy неплохие, но видимо, они тебе дали слишком мало понимания.
Если тебе книга руби для романтиков, показалось сложной или много воды, попробуй начать читать
`Head First. Изучаем Ruby - Дж. Макгаврен`.

в любом случае тебе нужно понимать, что такое возвращаемое значение, область видимости(scope) и много чего, что видимо ты пока не понимаешь, раз пишешь такое
```rb
class Stack
  a = []
  a.push "c"
  a.push "p"
  a.push "u"
  a.pop 
  puts a 
...
```

2022-08-04 15:48 UTC, daniil934 commented
Сначала я разбирался как работают методы без Rspec, поэтому я в методах писал puts и вызывал их напрямую что бы понять как все работает.
```rb
class Stack
  attr_reader :a

  def initialize
    @a = []
  end

  def push(arg)
    a << arg
    puts a
  end

  def pop
    a.pop 
    puts a
  end

  def peek
    puts a.last # вот тут я еще не до конца уверен, я писал a.peek, но мне вызывало ошибку про то что метода peek не существует, 
                # я не совсем понял понял почему так.
  end
end

stac = Stack.new
stac.push("a")
stac.push("b")
stac.push("c")
stac.pop
stac.peek
```
После того как разобрался я добавил rspec, запустил тесты и они заработали.
```rb
class Stack
  attr_reader :a

  def initialize
    @a = []  
  end

  def push(arg)
    a << arg
  end

  def pop
    a.pop 
  end

  def peek
    a.last
  end
end 

RSpec.describe Stack do
  it 'pushes element on top of stack(кладёт элемент на стек)' do
    stack = Stack.new
    stack.push('a')
    stack.push('b')
    expect(stack.a).to eq ['a', 'b']
  end

  it 'removes element from stack(удаляет элемент из стека)' do
    stack = Stack.new
    expect(stack.pop).to eq nil
    stack.push('a')
    stack.push('b')
    expect(stack.pop).to eq 'b'
    expect(stack.pop).to eq 'a'
    expect(stack.pop).to eq nil
  end

  it 'shows element on top of stack(показывает верхний элемент на стеке)' do
    stack = Stack.new
    stack.push('a')
    stack.push('b')
    expect(stack.a).to eq ['a', 'b']
    expect(stack.peek).to eq 'b'
    expect(stack.a).to eq ['a', 'b']
  end
end
```

2022-08-05 09:35 UTC, sjnm8 approved these changes

2022-08-05 09:36 UTC, merged