added stack file
daniil934/test1 pull request #5
Opened 2022-08-12 15:54 UTC by daniil934

```rb
class Stack
  attr_reader :a
  attr_accessor :c

  def initialize(size = 0)
    @a = Array.new(size)
    @c = (size * 2) + 1
  end

  def push(arg = 0)
    a << arg
    b = a.length
    if b > @c
      return "stack overflow"
    end
  end

  def pop
    a.pop 
  end

  def peek
    a.last
  end

  def empty?
    a.empty?
  end

  def empty
    a
  end
  def full?
    b = a.length
    if (b+1) == @c
      return true
    end
  end
end 

RSpec.describe Stack do
  it 'pushes element on top of stack(кладёт элемент на стек)' do
    stack = Stack.new
    stack.push('a')
    stack.push('b')
    expect(stack.a).to eq ['a', 'b']
  end

  it 'returns error if stack overflows' do
    stack = Stack.new(2)
    stack.push('a')
    stack.push('b')
    stack.push('d')
    expect(stack.push).to eq("stack overflow")
  end

  it 'removes element from stack(удаляет элемент из стека)' do
    stack = Stack.new
    expect(stack.pop).to eq nil
    stack.push('a')
    stack.push('b')
    expect(stack.pop).to eq 'b'
    expect(stack.pop).to eq 'a'
    expect(stack.pop).to eq nil
  end

  it 'returns true when stack is empty' do
    stack = Stack.new(0)
    expect(stack.empty?).to eq true
  end

  it 'returns nil when stack is empty' do
    stack = Stack.new(0)
    expect(stack.pop).to eq nil
    expect(stack.peek).to eq nil
  end

  it 'returns true when stack is full' do
    stack = Stack.new(2)
    stack.push('a')
    stack.push('b')
    expect(stack.full?).to eq true
  end

  it 'shows element on top of stack(показывает верхний элемент на стеке)' do
    stack = Stack.new
    stack.push('a')
    stack.push('b')
    expect(stack.a).to eq ['a', 'b']
    expect(stack.peek).to eq 'b'
    expect(stack.a).to eq ['a', 'b']
  end
end

```

2022-08-13 21:56 UTC, sjnm8 reviewed
Не добавляй ненужные папки.
Сделай просто 2 файла, в одном класс стека, в другом тесты.(Файл со стеком нужно подключить в файл тестов, смотри `require`, чтобы класс `Stack` был доступен в файле с тестами)

Файлы с тестами, нужно называть с окончанием `_spec.rb`, в таком случае они запускаются автоматически, если запустить rpsec в папке с тестами. Пример `stack_spec.rb`.

2022-08-13 21:56 UTC, sjnm8 commented on rb2/stack4.rb
> +  attr_accessor :c
Старайся называть переменные так, чтобы было понятно, что они значат.
Что такое 'с' непонятно, нужно называть 'size`. А еще лучше назвать `deep`, так как `size` это размер массива, а у стека "глубина"

2022-08-13 21:56 UTC, sjnm8 commented on rb2/stack4.rb
> +    @c = (size * 2) + 1
Для чего ты тут умножаешь на 2 и прибавляешь 1?
У тебя глубина стека больше на 1, чем задаешь параметром.

По логике нужно сделать проверку, что size не меньше 1(кстати, тут ты параметр нормально назвал) и если меньше выдавать ошибку. Только не строкой, как ты сделал в методе push(и там тоже надо явно выдавать ошибку) с помощью `raise`

2022-08-13 21:56 UTC, sjnm8 commented on rb2/stack4.rb
> +    if b > @c
Намудрил. Тебе нужно просто перед добавлением элемента в массив сделать проверку, что размер не превышен.
```rb
def push(arg) # тут не нужно значение по умолчанию
  raise 'StackOverFlow' if a.length == size # тут имеется ввиду @size, ты написал для @c attr_accessor, но почему то всё равно обращаешься через @ 
  a << arg
end
```

2022-08-13 21:56 UTC, sjnm8 commented on rb2/stack4.rb
> +  def empty
данный метод не нужен

2022-08-13 21:56 UTC, sjnm8 commented on rb2/stack4.rb
> +    if (b+1) == @c
Тут тоже не ясна логика. Тебе нужно всего лишь сделать проверку, равняется ли длинна массива - размеру.
```rb
def full?
  a.length == size # По умолчанию из функции возвращается результат последнего выражения
end
```
Зачем ты тут прибавляешь 1 ?

2022-08-13 21:56 UTC, sjnm8 commented on rb2/stack4.rb
> +    expect(stack.push).to eq("stack overflow")
Это проверка на возврат строки, а не ошибки.
Вот пример, как проверяется ошибка https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/raise-error-matcher

2022-08-13 22:13 UTC, sjnm8 requested changes
В целом справился, нормально. Отпишись по вопросам и поправь замечания.
И попробуй решить задачу со "скобочками"

Описание задачи:
Класс получает на вход строку со скобками. Примеры - `(())((()))()(())` и возвращает true, каждая открытая скобка имеет пару с закрытой. `()()` - true. `(()(` - false, последня скобка не имеет пары. `(()(()` - false, тоже пары не совпадают.

Подскажу тебе алгоритм действий:
1. Разбиваешь строку в массив.
2. В цикле обходишь массив. Когда встречаешь открывающую скобку, кладешь ее в стек. Если встречаешь закрывающую скобку, то убираешь открывающую из стека.
3. Если все скобки совпали, в конце цикла, стек должен быть пустой.
4. Нужно учесть пограниченые моменты, например, строка `()))`. Здесь в цикле, на 2ой закрывающей скобке, у тебя уже стек будет пустой(несмотря на то, что цикл еще не закончился) и нужно вернуть false, так как уже понятно, что скобки неправильно написаны.

Задача подразумевает, упрощенную реализацию, проверки математических выражений.
Мы просто упрощаем её. Вместо `(1 + 2) * 3 / (4 + 5) * 6` мы берем сразу строку `()()`
или другой пример `(2 * (1 + 3) + 4) * 2 ` - `(())`

После этого, будем считать, что задачи по стеку завершены. После этого перейдем к очереди (queue)

2022-08-25 11:28 UTC, daniil934 commented
По поводу стека, я сделал так замудренно, потому что a.length начинаеться не с 0, он засчитывает nil в массиве и при
добавлении значений получаеться a.length выдает в 2 раза большее значение.
```rb
[nil, nil, nil, "k", "b", "n"]
```
тут 6 значений, хотя в массиве я занес всего 3. Я поэтому не понял как это сделать по другому.
А по задаче со скобками, у меня все получилось, я скинул 2 файла в ветку и удалил лишние папки. И вот эта задача одним кодом:
```rb
class Parenthesis
  attr_accessor :arg
  attr_accessor :str
  attr_accessor :split_arr
  attr_accessor :a
  def initialize(str)
    @a = Array.new
    @str = str
  end

  def split_m
    @split_arr = str.split("")
  end

  def cycle
    return false if split_arr.count(")") != split_arr.count("(")
    split_arr.each do |i|
      a << "(" if i == "(" 
      a.pop if i == ")" 
    end
    return a.empty? ? true : false
  end
end

RSpec.describe Parenthesis do
  it 'Returns true' do
    par = Parenthesis.new("(1 + 2) * 3 / (4 + 5) * 6")
    par.split_m
    par.cycle
    expect(par.cycle).to be true
  end

  it 'Returns false' do
    par = Parenthesis.new(")(1 + 2) * 3 / (4 + 5) * 6(")
    par.split_m
    par.cycle
    expect(par.cycle).to be false
  end
end
```

2022-08-27 08:54 UTC, sjnm8 requested changes

2022-08-27 08:54 UTC, sjnm8 commented on parenthesis.rb
> +  def split_m
Этот метод не нужен, тебе приходиться каждый раз его вызывать перед cycle.
Разбить на строку можно и в методе `initialize`, и тогда вызов будет проще
`Parenthesis.new("(1 + 2) * 3 / (4 + 5) * 6").cycle`

2022-08-27 08:54 UTC, sjnm8 commented on parenthesis.rb
> +    @a = Array.new
Можно использовать и массив, но сделай лучше, чтобы тут использовался, написанный ранее стек.

2022-08-27 08:54 UTC, sjnm8 commented on parenthesis.rb
> +    return false if split_arr.count(")") != split_arr.count("(")
Решение работает, однако оно не оптимально.
Смотри, что ты делаешь:
```rb
return false if split_arr.count(")") != split_arr.count("(")
```
У тебя сначала метод count ищет `)`, то есть он делает обход всего массива и смотрит, является ли элемент скобкой.
Потом он еще раз обходит массив и ищёт `(`
И потом ты еще раз проходишь по массиву в циле
```rb
split_arr.each do |i|
      a << "(" if i == "(" 
      a.pop if i == ")" 
    end
```

получается в сумме ты три раза обходишь один и тот же массив.
Для маленького решения, это может сгодиться. А представь если у тебя массив был бы на 1 млн элементов, и ты 3 раза обходишь его, получается 3 млн шагов.
Пример `)(((((((((((((((.....и далее тут 3 миллиона скобок`
Твое решение выполнит 3 млн шагов, хотя тут достаточно 1ого шага, чтобы понять, что скобки не совпадают.

Поэтому нужно просто обойти в цикле 1 раз строку со скобками(которую ты разбил на массив, можно еще воспользоваться методом each_char и не разбивать строку на массив).

В задаче выше `)((((((((((((((((((((.....(((`, на первом же шаге, встречаем закрывающую скобку, проверяем, что стек при этом пустой и выдаем false.

2022-08-27 08:54 UTC, sjnm8 commented on parenthesis.rb
> +  attr_accessor :arg
Для чего эта инстанс переменная? Забыл убрать?

2022-08-27 08:54 UTC, sjnm8 commented on parenthesis_spec.rb
> +    expect(par.cycle).to be false
2 раза вызываешь par.cycle, достаточно одного с `expect`

2022-08-27 08:54 UTC, sjnm8 commented on parenthesis_spec.rb
> +  it 'Returns true' do
Тесты не только проверяют твоё решение, но и описывают для других разработчиков, что делает твой класс. Старайся в таком случае писать в стиле `returns true when parenthesis match`

2022-08-27 12:00 UTC, daniil934 commented
```rb
class Parenthesis
  attr_accessor :arg, :str, :a
  def initialize(str, size = 0)
    @a = Array.new(size)
    @str = str
  end

  def cycle
    return false if a[0] == ")"
    str.each_char do |i|
      return false if str.count(")") != str.count("(")
      a.push(i) if i == "(" 
      a.pop if i == ")" 
    end
    return a.empty? ? true : false
  end

  def push(arg = 0)
    a << arg
  end
end

RSpec.describe Parenthesis do
  it 'returns true when parenthesis match' do
    par = Parenthesis.new("(1 + 2) * 3 / (4 + 5) * 6")
    expect(par.cycle).to be true
  end

  it 'returns false when parenthesis mismatch' do
    par = Parenthesis.new(")(1 + 2) * 3 / (4 + 5) * 6(")
    expect(par.cycle).to be false
  end
end
```

2022-08-27 12:37 UTC, sjnm8 commented
Твоё первое решение было такое:
```rb
  def cycle
    return false if split_arr.count(")") != split_arr.count("(")
    split_arr.each do |i|
      a << "(" if i == "(" 
      a.pop if i == ")" 
    end
    return a.empty? ? true : false
  end
end
```

Пример, у нас массив `['(', '(', ')', ')']`

Как работает эта строка
```rb
return false if split_arr.count(")") != split_arr.count("(")
```

1. Сначала выполняется это выражение. `split_arr.count(")") != split_arr.count("(")` 

-   Выполняется `split_arr.count(")")`. Когда ты вызываешь метод `count`, внутри языка запускается цикл, который обходит массив. То есть такой же each, но он спрятан внутри реализации метода count. Возвращает число.(В нашем примере 2, для этого нам пришлось посмотреть 4 элемента)
-  Выполняется `split_arr.count("(")`. Тоже самое, что и выше. Результат 2, пройдено 4 элемента
- Далее сравниваются 2 числа

2 Мы возвращаем false, на основе результата сравнения

Далее у тебя идет цикл 
```rb
 split_arr.each do |i|
      a << "(" if i == "(" 
      a.pop if i == ")" 
    end
```
Тут ты еще раз проходишь по массиву(На примере 4)
Всего у тебя 12 шагов (3 раза по 4)

Вторая твоя реализация
```rb
def cycle
    return false if a[0] == ")"
    str.each_char do |i|
      return false if str.count(")") != str.count("(")
      a.push(i) if i == "(" 
      a.pop if i == ")" 
    end
    return a.empty? ? true : false
  end
```

Тут ты сделал еще хуже. 
Теперь у тебя вначале идет цикл. Ты проходишь его 4 раза(4 шага). Однако из-за того, что ты внес проверку на кол-во скобок внутрь цикла, у тебя на каждом шаге повторяется 2 раза вызов метода `count`(2 раза по 4 шага).
И теперь вместо 12 шагов, у тебя 4 шага внутри которых каждый раз еще 8. то есть 36 шагов. Понял?

Тебе нужно решить эту задачу в 4 шага.
```rb
arr = `['(', '(', ')', ')']`
arr.each do |el|
# 1 шаг цикла элемент '('. Т.к. это открывающая скобка, ты кладешь ее на стек.
# 2 шаг цикла элемент '('. Т.к. это открывающая скобка, ты кладешь ее на стек.
# 3 шаг цикла элемент ')'. Т.к это закрывающая скобка, просто удаляешь элемент со стека.
# 4 шаг цикла элемент ')'. Т.к это закрывающая скобка, просто удаляешь элемент со стека.
end

stack.empty? ? true : false
```

Вот и всё. Для ситуации с `)(((`

```rb
arr.each do |el|
# 1 шаг цикла элемент ')'. Т.к это закрывающая скобка, просто удаляешь элемент со стека. Однако стек пуст, поэтому сразу возвращаем false и заканчиваем цикл.
end
```

Осталось записать это в коде. Как упражнение, добавь в класс счётчик, который считает сколько шагов цикла ты сделал. и в тестах проверяешь.

Проверку с count просто удали и всё. Используй стек, ты же писал его раньше.

Замечания по коду

```rb
def push(arg = 0)
    a << arg
  end
``` 
Для чего это? Ты не используешь это.

Ты задаешь массиву размер, но нигде нет проверок. Просто не задавай размер в таком случае. и еще раз, там должен быть стек, класс который писал ранее. Если ты его уже удалил, хрен с ним, используй массив. На будущее ничего не удаляй. Просто добавляй, так как я буду вливать все в мастер, и старый код может быть нужным.

return false if a[0] == ")" тоже не нужно, ты и так на первом шаге, увидишь что стек(или массив) пустой и можно прямо внтури цикла возвращать false.

2022-08-27 13:04 UTC, daniil934 commented
```rb
class Parenthesis
  attr_accessor :arg, :str, :a
  def initialize(str, size = 0)
    @a = Array.new(size)
    @str = str
  end

  def cycle
    str.each_char do |i|
      a.push(i) if i == "(" 
      a.pop if i == ")"
    end
    return a.empty? ? true : false
  end
end

RSpec.describe Parenthesis do
  it 'returns true when parenthesis match' do
    par = Parenthesis.new("(1 + 2) * 3 / (4 + 5) * 6")
    expect(par.cycle).to be true
  end

  it 'returns false when parenthesis mismatch' do
    par = Parenthesis.new(")(1 + 2) * 3 / (4 + 5) * 6(")
    expect(par.cycle).to be false
  end

  it 'returns false when parenthesis mismatch' do
    par = Parenthesis.new("(()))")
    expect(par.cycle).to be false
  end
end
```
Эту строку
```rb
return false if split_arr.count(")") != split_arr.count("(")
```
Я написал для случая `"( ( ) ) )"` , потому что, когда скобка в конце закрывающая, массив все равно остаеться пустой и возвращаеться true, я добавил еще одну проверку ну этот случай.
А поповоду стека, у меня остался код класа стек, я просто не пронимаю как его тут использовать вместо массива.

2022-08-27 14:45 UTC, sjnm8 commented
```rb
irb(main):083:0> p = Parenthesis.new(")")
=> #<Parenthesis:0x00007fe37d7ee4c0 @a=[], @str=")">
irb(main):084:0> p.cycle
=> true
irb(main):085:0> 
```
Твой код показывает, что `)` - правильная последовательность.

> А поповоду стека, у меня остался код класа стек, я просто не пронимаю как его тут использовать вместо массива.
```rb
def initialize(str) # size тут не нужен
@str = str
@stack = Stack.new # вместо @a
end

...

def cycle # Тоже самое с этим методом. Назови его `match?`, тогда будет понятно, что он делает. А так ты называешь его по внутренней реализации. А что если я буду использовать не цикл, а что-то другое?
  str.each_char do |char| # не называй i,a,q,abc,qwerty и тд, по таким названия не понятно, что это. 
      stack.push(char) if char == "(" 
      stack.pop if char == ")"
    end
end
```

Забыл снова убрать :arg, он у тебя не используется
```rb
class Parenthesis
  attr_accessor :arg, :str, :a
...
end
```

2022-08-27 14:46 UTC, sjnm8 commented
Поправь ошибку кода, напиши на нее тест, и запушь всё, и я закрою эту задачу

2022-08-28 13:00 UTC, daniil934 commented
```rb
class Parenthesis
  attr_accessor :str, :stack
  def initialize(str)
    @str = str
    @stack = Stack.new
  end

  def match?
    str.each_char do |char|
      stack.push(char) if char == "(" 
      stack.pop if char == ")"
    end
    return stack.empty? ? true : false
  end
end

class Stack
  attr_reader :a
  attr_accessor :deep
  def initialize
    @a = Array.new
  end

  def push(arg = 0)
    a << arg
  end

  def pop
    a.pop 
  end

  def empty?
    a.empty?
  end
end

RSpec.describe Parenthesis do
  it 'returns true when parenthesis match' do
    par = Parenthesis.new("(1 + 2) * 3 / (4 + 5) * 6")
    expect(par.match?).to be true
  end

  it 'returns false when parenthesis mismatch' do
    par = Parenthesis.new(")(1 + 2) * 3 / (4 + 5) * 6(")
    expect(par.match?).to be false
  end
end
```

2022-08-28 19:47 UTC, sjnm8 commented
```rb
irb(main):037:0> p = Parenthesis.new(')')
=> 
#<Parenthesis:0x00007f08fb5a6a80                                 
...                                                              
irb(main):038:0> p.match?
=> true
irb(main):039:0> 
```

Ты так и не поправил эту ошибку. Здесь должно быть `false`

2022-08-28 19:48 UTC, sjnm8 commented
В остальном всё нормально

2022-08-29 09:35 UTC, daniil934 commented
```rb
class Parenthesis
  attr_accessor :str, :stack
  def initialize(str)
    @str = str
    @stack = Stack.new
  end

  def match?
    str.each_char do |char|
      return false if str[0] == ")"
      stack.push(char) if char == "(" 
      stack.pop if char == ")"
    end
    return stack.empty? ? true : false
  end
end

class Stack
  attr_reader :a
  attr_accessor :deep
  def initialize
    @a = Array.new
  end

  def push(arg = 0)
    a << arg
  end

  def pop
    a.pop 
  end

  def empty?
    a.empty?
  end
end

RSpec.describe Parenthesis do
  it 'returns true when parenthesis match' do
    par = Parenthesis.new("(1 + 2) * 3 / (4 + 5) * 6")
    expect(par.match?).to be true
  end

  it 'returns false when parenthesis mismatch' do
    par = Parenthesis.new(")(1 + 2) * 3 / (4 + 5) * 6(")
    expect(par.match?).to be false
  end

  it 'returns false when parenthesis mismatch' do
    par = Parenthesis.new(")")
    expect(par.match?).to be false
  end
end
```

2022-08-29 11:53 UTC, sjnm8 commented
```rb
irb(main):037:0> p = Parenthesis.new('())').match?
=> true
```
Все равно остался баг.

1. Не пиши такие решения, как `return false if str[0] == ")"`. Это не гибко, а что, если у тебя будет выражение `-(5 + 2) * 3` ? Или например, попросят, чтобы класс поддерживал `{,[` разные виды скобок.
2. Это не решает баг, когда встречаешь закрывающую скобку, нужно проверить, не пуст ли стек, если пуст сразу `return false`
3. Нужно больше тестов. Ты тесты для того и пишешь, чтобы отловить баги. Видишь, как я 2 простыми примерами `)` и `())`, нашёл баги.

2022-08-31 09:32 UTC, sjnm8 commented
В общем нормально. Единственое, тут можно написать проще.
Еще, следи за отступами, используй везде 2 проблема.
```rb
def match?
  str.each_char do |char|
    stack.push(char) if char == "(" 
    if char == ")"
      return false if stack.empty?
    end
    stack.pop if char == ")" # Эта проверка уже есть выше, ее можно переместить туда
  end
  return stack.empty? ? true : false
end
```

Получится
```rb
str.each_char do |char|
  stack.push(char) if char == "(" 
  if char == ")"
    return false if stack.empty?

    stack.pop if char == ")"
  end
end
return stack.empty? ? true : false
```

2022-08-31 09:33 UTC, merged